"""Hand-authored changed-art review variants for the course's late command cards.

The generator owns card assembly.  This module owns the review studies that
make the same taught operation useful on a different piece of animation art.
Every entry is literal source art: no marker injection, whole-buffer rewrite,
or imported corpus frame is used here.
"""


def _review(start, target, expected, recipe, source_ref, prompt, hint, **extra):
    """Keep the repeated review schema readable without deriving art."""
    row = {
        "start": start,
        "target": target,
        "expected": expected,
        "recipe": recipe,
        "cursor": "^",
        "source_ref": source_ref,
        "prompt": prompt,
        "hint": hint,
    }
    row.update(extra)
    return row


REVIEW_VARIANTS = {
    "M11.AT": [
        _review(
            ["  ____/", "< / / / |:.", "  ¯¯¯¯\\"],
            ["  ____/", "< \\ \\ \\ |:.", "  ¯¯¯¯\\"],
            r"2G:s@/@\\@g<CR>",
            [["2G", "land on the copied middle rail"],
             [r":s@/@\\@g<CR>", "replace every slash in that rail with a backslash"]],
            "ascii-art-authoring §§4.4,9h; authored missile rail A",
            "On the changed missile rail, turn every diagonal slash into its backslash counterpart with the taught substitute delimiter.",
            "The acting row has three slash strokes; use @ as the delimiter and leave both outer rows untouched.",
        ),
        _review(
            ["   __/", "<  /   / |::", "  ¯¯¯\\"],
            ["   __/", "<  \\   \\ |::", "  ¯¯¯\\"],
            r"2G:s@/@\\@g<CR>",
            [["2G", "land on the copied middle rail"],
             [r":s@/@\\@g<CR>", "replace the two diagonal strokes on that rail"]],
            "ascii-art-authoring §§4.4,9h; authored missile rail B",
            "On the second changed missile rail, replace only its two slash strokes using @ so the frame's rails remain registered.",
            "Count the two slash landmarks on row 2; the delimiter is @, not a slash.",
        ),
    ],
    "M11.COL": [
        _review(
            ["  __/___", "< /  /|:.  ", "  ¯¯¯¯¯\\"],
            ["  __/___", "< /  /|:.  ", "  ¯¯¯¯¯\\"],
            ":set virtualedit=all<CR>2G12|",
            [["2G", "land on the ragged comparison rail"],
             ["12|", "inspect display column 12 without inserting a cell"]],
            "ascii-art-authoring §§4.4,9h; authored ragged missile A",
            "Enable virtual editing and land on display column 12 of the changed ragged rail without changing its text.",
            "The middle rail ends before the requested display column; 12| is a cursor landing, not an insertion.",
            cursor_after=[2, 11],
        ),
        _review(
            ["    _/", "<//   |::' ", "  ¯¯¯\\"],
            ["    _/", "<//   |::' ", "  ¯¯¯\\"],
            ":set virtualedit=all<CR>2G12|",
            [["2G", "land on the short double-slash rail"],
             ["12|", "inspect its empty registered column 12"]],
            "ascii-art-authoring §§4.4,9h; authored ragged missile B",
            "On the second short rail, use virtual column motion to inspect column 12 while preserving the double-slash edge.",
            "Do not insert or pad the row: the operation is only a display-column landing.",
            cursor_after=[2, 11],
        ),
    ],
    "M11.INS": [
        _review(
            ["  __/___", "< /  /|:.", "  ¯¯¯¯¯\\"],
            ["  __/___", "< /  /|:.  |", "  ¯¯¯¯¯\\"],
            ":set virtualedit=all<CR>2G12|i|<Esc>",
            [["2G12|", "land on the empty registered trail column"],
             ["i|<Esc>", "insert one comparison edge and return to Normal mode"]],
            "ascii-art-authoring §§4.4,9h; authored ragged missile A",
            "Insert one vertical comparison edge at display column 12 on the changed missile rail.",
            "Reach the empty virtual column first, insert one |, and keep every pre-existing diagonal in place.",
        ),
        _review(
            ["   __/", "<//   |::", "  ¯¯¯\\"],
            ["   __/", "<//   |::  |", "  ¯¯¯\\"],
            ":set virtualedit=all<CR>2G12|i|<Esc>",
            [["2G12|", "land on the empty registered trail column"],
             ["i|<Esc>", "insert one vertical edge and return to Normal mode"]],
            "ascii-art-authoring §§4.4,9h; authored ragged missile B",
            "Add one registered vertical edge to the changed short rail at virtual column 12.",
            "Only the empty trail cell is new; do not redraw the double-slash or its trailing punctuation.",
        ),
    ],
    "M2.DW": [
        _review(
            ["| one two three |", "|   /\\   /\\   |", "|_______________|"],
            ["| two three |", "|   /\\   /\\   |", "|_______________|"],
            "ggfodw",
            [["ggfo", "land on the first word's o"],
             ["dw", "delete that word and its following separator"]],
            "ascii-art-authoring §2; authored face banner A",
            "On the three-word face banner, delete only the first word-sized span with dw and preserve the two remaining labels.",
            "The first word is still the one landmark; the second and third words prove that dw stops at the next word.",
        ),
        _review(
            ["+ one  blue two |", "+  /\\   /--\\  |", "+===============+"],
            ["+ blue two |", "+  /\\   /--\\  |", "+===============+"],
            "ggfodw",
            [["ggfo", "land on the first word's o"],
             ["dw", "delete the first word span without touching blue"]],
            "ascii-art-authoring §2; authored face banner B",
            "Remove the first one-word label from the changed banner with dw while the blue and two labels remain.",
            "Use the first o as the landing landmark; this art's plus rails and double separator are not acting cells.",
        ),
    ],
    "M2.DE": [
        _review(
            ["| one two three |", "|   /\\   /\\   |", "|_______________|"],
            ["|  two three |", "|   /\\   /\\   |", "|_______________|"],
            "ggfode",
            [["ggfo", "land on the first word's o"],
             ["de", "delete through its final glyph but keep the following space"]],
            "ascii-art-authoring §2; authored word-end banner A",
            "Use de on the changed word-end study so the first word disappears but its separator remains before two.",
            "Contrast the visible double gap after de with dw: the following word and its leading space remain.",
        ),
        _review(
            ["+ one blue two |", "+  /\\  \\__/  |", "+===============+"],
            ["+  blue two |", "+  /\\  \\__/  |", "+===============+"],
            "ggfode",
            [["ggfo", "land at the first word's o"],
             ["de", "remove through the word end and preserve its following space"]],
            "ascii-art-authoring §2; authored word-end banner B",
            "Delete the first one-word label through its final glyph with de, leaving the changed blue/two banner registered.",
            "The command stops at the word's final glyph; do not take the separating space as dw would.",
        ),
    ],
    "M2.D2W": [
        _review(
            ["| red   blue   green |", "|    /\\     /\\    |", "|____________________|"],
            ["| green |", "|    /\\     /\\    |", "|____________________|"],
            "ggfrd2W",
            [["ggfr", "land on the first WORD's r"],
             ["d2W", "delete the first two blank-separated WORD spans"]],
            "ascii-art-authoring §2; authored counted-WORD banner A",
            "Delete the first two counted WORD spans from the changed wide banner, leaving green as the only label.",
            "The repeated blank gaps are separators; d2W consumes red and blue but stops before green.",
        ),
        _review(
            ["+ red  cobalt  green +", "+   /\\    \\__/    +", "+===================+"],
            ["+ green +", "+   /\\    \\__/    +", "+===================+"],
            "ggfrd2W",
            [["ggfr", "land on the first WORD's r"],
             ["d2W", "delete two counted WORD spans in one bounded edit"]],
            "ascii-art-authoring §2; authored counted-WORD banner B",
            "Use the taught count to remove red and cobalt from the changed banner while preserving the green end cap.",
            "Start at the r in red; the second WORD is cobalt, not a third target.",
        ),
    ],
    "M2.TEN": [
        _review(
            [" /---\\", "|  .  |", "| \\_/ |", " \\___/",
             " /---\\", "|  O  |", "| /_\\ |", " \\___/",
             " /---\\", "|  -  |", "| \\_/ |", " \\___/"],
            [" /---\\", "|  .  |", "| \\_/ |", " \\___/",
             " /---\\", "|  O  |", "| /_\\ |", " \\___/",
             " /---\\", "|  -  |", "| \\_/ |", " \\___/"],
            "10G",
            [["10G", "jump to the tenth row of the three-frame strip"]],
            "ascii-art-authoring §9e; authored three-frame count study A",
            "On the changed three-frame strip, jump to line 10 with one two-digit count and leave every drawing row unchanged.",
            "The operation is a line-count landing: the third frame's marker row is line 10.",
            cursor_after=[10, 1],
        ),
        _review(
            [" +===+", " | o |", " |/\\|", " +===+",
             " +===+", " | O |", " |\\/|", " +===+",
             " +===+", " | - |", " |/\\|", " +===+"],
            [" +===+", " | o |", " |/\\|", " +===+",
             " +===+", " | O |", " |\\/|", " +===+",
             " +===+", " | - |", " |/\\|", " +===+"],
            "10G",
            [["10G", "land on line 10 of the alternate three-frame strip"]],
            "ascii-art-authoring §9e; authored three-frame count study B",
            "Use the taught two-digit count to reach the tenth line of the alternate strip without editing its frame geometry.",
            "Count from the top; line 10 is the minus-marked row of the final frame.",
            cursor_after=[10, 1],
        ),
    ],
    "M15.APP": [
        _review(
            ["| hatch |", "|  /\\  |", "|______|"],
            ["| h!atch |", "|  /\\  |", "|______|"],
            "ggfha!<Esc>",
            [["ggfh", "land on the h that receives the following glyph"],
             ["a!<Esc>", "append ! after h and return to Normal mode"]],
            "ascii-art-authoring §2; authored append study A",
            "Append one glyph after the h in the changed hatch label, leaving its surrounding frame rails registered.",
            "Use a after the h; the exclamation mark belongs between h and the existing a.",
        ),
        _review(
            ["+ h!de |", "+ /\\  |", "+------|"],
            ["+ h!!de |", "+ /\\  |", "+------|"],
            "ggfha!<Esc>",
            [["ggfh", "land on the existing h"],
             ["a!<Esc>", "append a second visible ! after h and return to Normal mode"]],
            "ascii-art-authoring §2; authored append study B",
            "Append another glyph after the h in the changed hide label; preserve the existing exclamation already after it.",
            "The acting span is still the h-to-next-glyph gap, so a inserts before the existing !.",
        ),
    ],
    "M15.APPA": [
        _review(
            ["| hi ~ |", "|  /\\ |", "|______|"],
            ["| hi ~ |!", "|  /\\ |", "|______|"],
            "ggfhA!<Esc>",
            [["ggfh", "land on the first row's h"],
             ["A!<Esc>", "append ! at the end of the whole row and return to Normal mode"]],
            "ascii-art-authoring §2; authored line-end append study A",
            "Append one final glyph at the end of the changed top rail with A, not immediately after the cursor.",
            "A moves to the row end; the new ! follows the closing rail glyph.",
        ),
        _review(
            ["+ hi  ]", "+ /\\ ]", "+======+"],
            ["+ hi  ]!", "+ /\\ ]", "+======+"],
            "ggfhA!<Esc>",
            [["ggfh", "land on the top-row h"],
             ["A!<Esc>", "append ! after the closing bracket at row end"]],
            "ascii-art-authoring §2; authored line-end append study B",
            "Use A to add one final glyph after the changed top row's bracket while preserving its lower rails.",
            "The end append belongs after ], regardless of the cursor's original h position.",
        ),
    ],
    "M15.MACR": [
        _review(
            ["| : = : |", "|_______|", "| shadow |"],
            ["| . = : |", "|_______|", "| shadow |"],
            "gg0qqf:r.q",
            [["gg0", "anchor the macro at the start of the material row"],
             ["qqf:r.q", "record q, replace the first colon with a dot, and stop recording"]],
            "ascii-art-authoring §2; authored macro material study A",
            "Record one bounded q macro that changes only the first colon in the material row to a dot.",
            "The first colon is the acting landmark; q records the find-and-replace and the final q stops cleanly.",
        ),
        _review(
            ["+ :: - : +", "+-------+", "+ shadow +"],
            ["+ .: - : +", "+-------+", "+ shadow +"],
            "gg0qqf:r.q",
            [["gg0", "anchor the macro at the start of the alternate material row"],
             ["qqf:r.q", "record q, replace only the first colon, and stop recording"]],
            "ascii-art-authoring §2; authored macro material study B",
            "Use the bounded q macro to soften the first colon in the alternate texture row without touching its second colon.",
            "There are multiple colons: f: selects the first one, proving the macro is anchored rather than a broad rewrite.",
        ),
    ],
    "M3.CW": [
        _review(
            ["| TODO :      |", "|   /\\       |", "|_____________|"],
            ["| done :      |", "|   /\\       |", "|_____________|"],
            "ggfTcwdone<Esc>",
            [["ggfT", "land on the T of the TODO token"],
             ["cw", "change exactly that word-sized token"],
             ["done<Esc>", "type the replacement and return to Normal mode"]],
            "ascii-art-authoring §9c; authored word-change study A",
            "Change the TODO label in the changed frame to done with cw while preserving the face rail and punctuation.",
            "The acting span is the TODO word; cw must not consume the following colon or spaces.",
        ),
        _review(
            ["+ TODO /  ~  +", "+  \\__/      +", "+============+"],
            ["+ done /  ~  +", "+  \\__/      +", "+============+"],
            "ggfTcwdone<Esc>",
            [["ggfT", "land on the T of the alternate TODO token"],
             ["cw", "change that token as one word"],
             ["done<Esc>", "enter the replacement and return to Normal mode"]],
            "ascii-art-authoring §9c; authored word-change study B",
            "Replace only TODO in the alternate face strip with done; the slash, tilde, and rails remain unchanged.",
            "Find the capital T, use cw for the one word, and type done before leaving Insert mode.",
        ),
    ],
    "M3.CA": [
        _review(
            ["| ( old )       |", "|    /\\        |", "|_______________|"],
            ["| new       |", "|    /\\        |", "|_______________|"],
            "gg0f(ca(new<Esc>",
            [["gg0f(", "land on the opening parenthesis"],
             ["ca(", "select both delimiters and their contents"],
             ["new<Esc>", "type the replacement and return to Normal mode"]],
            "ascii-art-authoring §9c; authored parenthesis study A",
            "Replace the whole parenthesized eye token with new using ca( on the changed face.",
            "ca( must remove both delimiters and old; the neighboring frame rails are not part of the object.",
        ),
        _review(
            ["+ ( dim )  /  +", "+   \\__/     +", "+============+"],
            ["+ new  /  +", "+   \\__/     +", "+============+"],
            "gg0f(ca(new<Esc>",
            [["gg0f(", "land on the alternate opening parenthesis"],
             ["ca(", "change the complete delimited object"],
             ["new<Esc>", "enter the replacement and return to Normal mode"]],
            "ascii-art-authoring §9c; authored parenthesis study B",
            "Use ca( to replace the dim parenthesized token in the alternate face while preserving the slash landmark.",
            "The slash after the closing delimiter proves the selection stops at the matching parenthesis.",
        ),
    ],
    "M3.Y0": [
        _review(
            ["| A / |", "| B - |", "| C \\ |", "| D . |"],
            ["| A / |", "| C \\ |", "| A / |", "| D . |"],
            'ggyyj1dd"0p',
            [["ggyy", "yank the complete first pose row"],
             ["j1dd", "move to and delete the next pose row"],
             ['"0p', "put the preserved zero-register row below the deletion"]],
            "ascii-art-authoring §9c; authored register-zero pose A",
            "Delete the second pose row and recover the first through register 0, preserving the changed slash and backslash landmarks.",
            "The copied A row must appear both at its original position and below C; the B row is the disposable one.",
        ),
        _review(
            ["+ top  / +", "+ cut  - +", "+ lower _+", "+ end  . +"],
            ["+ top  / +", "+ lower _+", "+ top  / +", "+ end  . +"],
            'ggyyj1dd"0p',
            [["ggyy", "yank the complete top pose row"],
             ["j1dd", "delete the following cut row"],
             ['"0p', "put the zero-register top pose below lower"]],
            "ascii-art-authoring §9c; authored register-zero pose B",
            "On the alternate pose stack, remove cut and put the preserved top row below lower with register 0.",
            "The slash, underscore, and plus frame edges make the moved row's identity visible after the delete.",
        ),
    ],
    "M3.MARK": [
        _review(
            ["| rail top  |", "| pass one  |", "| pass two  |", "| anchor art |", "| tail end  |"],
            ["| rail top  |", "| pass one  |", "| pass two  |", "| ancho! art |", "| tail end  |"],
            "gg4GmaG'a0frr!",
            [["gg4Gma", "set mark a on the anchor row"],
             ["G", "travel to the end of the strip"],
             ["'a", "return to the marked anchor line"],
             ["0frr!", "replace the first r on the marked row"]],
            "ascii-art-authoring §9c; authored meaningful-mark travel A",
            "Mark the fourth anchor row, travel to the tail, return with 'a, and change only its first r.",
            "The marked anchor is not the final row: the return jump must prove the mark, then frr! changes art in place.",
        ),
        _review(
            ["+ roof line +", "+ move left +", "+ move right+", "+ anchor rim+", "+ finish cap+"],
            ["+ roof line +", "+ move left +", "+ move right+", "+ ancho! rim+", "+ finish cap+"],
            "gg4GmaG'a0frr!",
            [["gg4Gma", "place mark a on the fourth anchor rim"],
             ["G", "travel past the moving rows to the finish cap"],
             ["'a", "return to the marked rim"],
             ["0frr!", "replace its first r without shifting width"]],
            "ascii-art-authoring §9c; authored meaningful-mark travel B",
            "Use a named mark to return from the finish cap to the alternate anchor rim, then replace its first r.",
            "Only the marked anchor changes; the two moving rows and the plus-framed finish remain untouched.",
        ),
    ],
    "M3.VD": [
        _review(
            ["| keep left |", "| keep mid  |", "| erase A   |", "| erase B   |", "| tail mark |"],
            ["| keep left |", "| keep mid  |", "| tail mark |"],
            "ggjjVjd",
            [["ggjjVj", "select the two erase rows linewise"],
             ["d", "delete only the selected complete rows"]],
            "ascii-art-authoring §9c; authored Visual-line pose A",
            "Select and delete the two erase rows in Visual-line mode, leaving the changed keep rails and tail.",
            "The linewise selection starts at erase A and ends at erase B; do not delete either neighboring pose row.",
        ),
        _review(
            ["+ hold one +", "+ hold two +", "+ cut left +", "+ cut right+", "+ return  +"],
            ["+ hold one +", "+ hold two +", "+ return  +"],
            "ggjjVjd",
            [["ggjjVj", "select both cut rows linewise"],
             ["d", "delete the selected cut rows and keep the return row"]],
            "ascii-art-authoring §9c; authored Visual-line pose B",
            "Remove the two cut rows from the alternate plus-framed pose using a complete Visual-line selection.",
            "V is linewise: the operation must consume cut left and cut right together, not their interior glyphs.",
        ),
    ],
    "M4.SIL": [
        _review(
            ["  ______", "< / / |::'", "  ¯¯¯¯¯\\"],
            ["  ______", "< / / |::'", "  ¯¯¯¯¯\\"],
            ":vnew<CR>:silent 0read #<CR>:bwipeout!<CR>",
            [[":vnew<CR>", "open a disposable reference window"],
             [":silent 0read #<CR>", "read the saved reference without the informational message"],
             [":bwipeout!<CR>", "wipe the disposable reference and return to the artwork"]],
            "ascii-art-authoring §§9f-9g; authored silent-reference pose A",
            "Inspect the changed reference pose in a disposable split with silent read, then close only that reference buffer.",
            "The final bwipeout! is part of the taught cleanup: one artwork window and one tab remain.",
        ),
        _review(
            ["   __/", "<//   |::'", "  ¯¯¯\\"],
            ["   __/", "<//   |::'", "  ¯¯¯\\"],
            ":vnew<CR>:silent 0read #<CR>:bwipeout!<CR>",
            [[":vnew<CR>", "open the disposable comparison split"],
             [":silent 0read #<CR>", "read the alternate saved pose silently"],
             [":bwipeout!<CR>", "close the comparison buffer without a write prompt"]],
            "ascii-art-authoring §§9f-9g; authored silent-reference pose B",
            "Use the silent reference workflow on the alternate ragged pose and leave its source window intact after cleanup.",
            "Read is informationally silent; bwipeout! closes the disposable buffer instead of saving it.",
        ),
    ],
    "M4.TRIM": [
        _review(
            ["  ______", "< / / |::'", "  ¯¯¯¯¯\\", "  ------"],
            ["< / / |::'", "  ¯¯¯¯¯\\", "  ------"],
            "ggdd",
            [["gg", "land on the imported duplicate row"],
             ["dd", "delete that complete row linewise"]],
            "ascii-art-authoring §§9f-9g; authored trim study A",
            "Trim the first duplicate row from the changed four-row reference with ggdd, leaving the three comparison rows.",
            "Only the imported top row is disposable; the diagonal, lower rail, and dash row stay in order.",
        ),
        _review(
            ["   __/", "<//   |::'", "  ¯¯¯\\", "  _-_-_"],
            ["<//   |::'", "  ¯¯¯\\", "  _-_-_"],
            "ggdd",
            [["gg", "land on the alternate imported top row"],
             ["dd", "remove exactly that duplicate line"]],
            "ascii-art-authoring §§9f-9g; authored trim study B",
            "Delete only the first imported duplicate from the alternate reference, preserving its ragged rail and final texture row.",
            "ggdd is linewise and bounded: the remaining three rows must not be joined or rewritten.",
        ),
    ],
    "M4.SCB": [
        _review(
            ["  ______", "< / / |::'", "  ¯¯¯¯¯\\"],
            ["  ______", "< / / |::'", "  ¯¯¯¯¯\\"],
            ":set scrollbind<CR>",
            [[":set scrollbind<CR>", "bind this changed comparison window to its partner"]],
            "ascii-art-authoring §§9f-9g; authored scrollbind pose A",
            "Enable scroll binding while viewing the changed three-row reference pose.",
            "This option changes comparison behavior, not the art: preserve every row and trailing rail exactly.",
            option_after="scrollbind",
        ),
        _review(
            ["   __/", "<//   |::'", "  ¯¯¯\\"],
            ["   __/", "<//   |::'", "  ¯¯¯\\"],
            ":set scrollbind<CR>",
            [[":set scrollbind<CR>", "bind the alternate comparison window's scrolling"]],
            "ascii-art-authoring §§9f-9g; authored scrollbind pose B",
            "Set scrollbind on the alternate ragged comparison pose without changing its registered text.",
            "The meaningful input is the comparison geometry; the expected result is unchanged art plus scrollbind enabled.",
            option_after="scrollbind",
        ),
    ],
    "M4.BD": [
        _review(
            ["+<o[]o>+", "+  []  +", "+<v[]v>+"],
            ["+<oo>+", "+    +", "+<vv>+"],
            "ggf[<C-v>2jld",
            [["ggf[<C-v>2j", "select the first eye cell through all three rows"],
             ["l", "extend the visual block across the second eye cell"],
             ["d", "delete only that rectangular block"]],
            "ascii-art-authoring §§9f-9g; authored block-delete eye study A",
            "Delete the rectangular two-column eye defect from the changed three-row face with blockwise Visual mode.",
            "The o/v eye marks remain beside the empty center; select both [] cells on every row and leave the surrounding face frame intact.",
        ),
        _review(
            ["* <{[]} > *", "*   []   *", "* <~[]~> *"],
            ["* <{} > *", "*      *", "* <~~> *"],
            "ggf[<C-v>2jld",
            [["ggf[<C-v>2j", "select the first lens cell through all three rows"],
             ["l", "extend it across the second lens cell"],
             ["d", "erase only the rectangular defect"]],
            "ascii-art-authoring §§9f-9g; authored block-delete lens study B",
            "Erase the two-cell lens defect from the alternate three-row study while preserving its brace and tilde contours.",
            "Start at the first [, extend one column to cover both [] cells, and delete that rectangle across all three rows.",
        ),
    ],
    "M13.BEB": [
        _review(
            ["| -- ~~ :: |", "| /\\  ..  |", "|__--__--__|"],
            ["| -! +~ ?: |", "| /\\  ..  |", "|__--__--__|"],
            "gg0WEr!2Wr?Br+",
            [["gg0WEr!2Wr?", "recreate the first and third cluster edits"],
             ["B", "return one WORD start to the middle cluster"],
             ["r+", "mark the returned cluster in place"]],
            "ascii-art-authoring §5; authored WORD-boundary texture A",
            "Traverse the changed texture clusters with W/E and 2W, return with B, and mark the middle cluster without changing the lower frame.",
            "The middle cluster is reached by B after the counted jump; preserve the slash-and-dot texture rows beneath it.",
        ),
        _review(
            ["+ -- ~~ :: +", "+ \\__/  -- +", "+==--==--==+"],
            ["+ -! +~ ?: +", "+ \\__/  -- +", "+==--==--==+"],
            "gg0WEr!2Wr?Br+",
            [["gg0WEr!2Wr?", "edit the first and third WORD clusters"],
             ["B", "move back one WORD start"],
             ["r+", "mark the returned middle cluster"]],
            "ascii-art-authoring §5; authored WORD-boundary texture B",
            "Use the taught boundary route on the alternate plus-framed texture and mark its middle cluster after returning with B.",
            "Only the first-row clusters are acting; the angular lower rows prove the changed art is not a border marker.",
        ),
    ],
    "M7.TC": [
        _review(
            ["| abc / |", "| def - |", "| ghi _ |"],
            ["| Abc / |", "| def - |", "| ghi _ |"],
            "ggfa~",
            [["ggfa", "land on the first lowercase label glyph"],
             ["~", "toggle that one glyph's case"]],
            "ascii-art-authoring §10; authored case-toggle strip A",
            "Toggle only the first label glyph in the changed three-row strip, leaving its diagonal and neighboring labels unchanged.",
            "The acting a is on row 1; ~ changes it to A without touching the two comparison rows.",
        ),
        _review(
            ["+ abc \\ +", "+ jkl . +", "+ mno : +"],
            ["+ Abc \\ +", "+ jkl . +", "+ mno : +"],
            "ggfa~",
            [["ggfa", "land on the alternate first label glyph"],
             ["~", "toggle its case in place"]],
            "ascii-art-authoring §10; authored case-toggle strip B",
            "Case-toggle the first a in the alternate plus-framed strip and preserve the slash, dot, and colon landmarks.",
            "Only the first row's a is acting; the lower rows make the changed strip substantive.",
        ),
    ],
    "M7.GTC": [
        _review(
            ["| red/blue |", "| low  high |", "| /\\  \\// |"],
            ["| RED/blue |", "| low  high |", "| /\\  \\// |"],
            "ggfrg~w",
            [["ggfr", "land on the first red word"],
             ["g~w", "toggle that word-sized object"]],
            "ascii-art-authoring §10; authored g-tilde word strip A",
            "Toggle the first red word in the changed slash-separated label with g~w, leaving blue and the lower geometry untouched.",
            "The slash is the word boundary: g~w changes red only, not blue or the comparison rows.",
        ),
        _review(
            ["+ red-blue +", "+ left right+", "+ <[]><> +"],
            ["+ RED-blue +", "+ left right+", "+ <[]><> +"],
            "ggfrg~w",
            [["ggfr", "land on red in the alternate label"],
             ["g~w", "toggle the word through its next boundary"]],
            "ascii-art-authoring §10; authored g-tilde word strip B",
            "Toggle red but not blue in the alternate hyphenated label with the taught g~w object motion.",
            "The hyphen bounds the acting word; the lower brackets are unchanged comparison art.",
        ),
    ],
    "M6.J": [
        _review(
            ["| left   |  ", "| right  |  ", "|  /\\   |  ", "|  ..   |  "],
            ["| left   |  | right  |  ", "|  /\\   |  ", "|  ..   |  "],
            "ggflJ",
            [["ggfl", "land on the first row's left landmark"],
             ["J", "join it to the following row with one separating space"]],
            "ascii-art-authoring §10; authored join-lines candle A",
            "Join the two changed candle-label rows with J and leave the diagonal and dotted base rows below them.",
            "J consumes the next complete row; preserve the double rail spacing and the lower two rows.",
        ),
        _review(
            ["+ rail left +  ", "+ right top +  ", "+ \\__/     +  ", "+  ..      +  "],
            ["+ rail left +  + right top +  ", "+ \\__/     +  ", "+  ..      +  "],
            "ggflJ",
            [["ggfl", "land on the first left landmark"],
             ["J", "join the second label row to it"]],
            "ascii-art-authoring §10; authored join-lines candle B",
            "Join the alternate plus-framed label rows with J while preserving its angular candle body and base.",
            "The first l in the top row is the landing landmark; the two lower rows must not be joined.",
        ),
    ],
    "M6.DDP": [
        _review(
            ["  /\\  ", " /==\\ ", "/____\\"],
            [" /==\\ ", "  /\\  ", "/____\\"],
            "ggddp",
            [["ggdd", "delete the complete upper contour row into the unnamed register"],
             ["p", "put it below the middle fill row to swap the adjacent frames"]],
            "ascii-art-authoring §10; authored adjacent-swap pyramid study A",
            "Swap the upper contour and middle fill rows of the changed pyramid strip with ddp, keeping the base frame fixed.",
            "The delete is linewise and the put is below the next row; the wide base remains the final playback frame.",
        ),
        _review(
            ["+ lead / +", "+ turn - +", "+ settle _+"],
            ["+ turn - +", "+ lead / +", "+ settle _+"],
            "ggddp",
            [["ggdd", "delete the lead playback row"],
             ["p", "put it below turn to swap the two adjacent frames"]],
            "ascii-art-authoring §10; authored adjacent-swap playback B",
            "Use ddp to swap the lead and turn frames in the alternate strip while the settle frame remains last.",
            "The slash and underscore make the moved lead row visible after the put; no row-wide rewrite is allowed.",
        ),
    ],
    "M8.O": [
        _review(
            ["|  flare  | ", "|   /\\   |  ", "|_________| "],
            ["|  new  |", "|  flare  | ", "|   /\\   |  ", "|_________| "],
            "ggflO|  new  |<Esc>",
            [["ggflO", "open one row above the first flare row"],
             ["|  new  |<Esc>", "type the new label and return to Normal mode"]],
            "ascii-art-authoring §9g-10; authored open-line walk A",
            "Open one row above the changed flare and type the new label, preserving the original walk rows below it.",
            "The inserted row is new; the original flare, diagonal, and ground rows retain their registration.",
        ),
        _review(
            ["+ flame / + ", "+   \\/   +  ", "+=========+ "],
            ["|  new  |", "+ flame / + ", "+   \\/   +  ", "+=========+ "],
            "ggflO|  new  |<Esc>",
            [["ggflO", "open above the alternate flame row"],
             ["|  new  |<Esc>", "type the new row label and return to Normal mode"]],
            "ascii-art-authoring §9g-10; authored open-line walk B",
            "Insert the new label above the alternate plus-framed flame with O and leave its angled walk body below.",
            "Find the l in flame; O opens above that row without rewriting the following art rows.",
        ),
    ],
    "M8.PAD": [
        _review(
            ["  taper  ", "   /\\   ", "  /__\\  "],
            ["", "", "  taper  ", "   /\\   ", "  /__\\  "],
            "ggftO<Esc>.",
            [["ggftO<Esc>", "open one blank padding row above the taper row"],
             [".", "repeat the same open-line change for the second padding row"]],
            "ascii-art-authoring §9g-10; authored frame-height torch study A",
            "Pad the changed three-row torch study with two blank rows using O and dot, preserving every original row below them.",
            "Find the first t in taper; dot repeats the open-line change rather than inserting text.",
        ),
        _review(
            ["+ title  + ", "+  base  + ", "+  foot  + "],
            ["", "", "+ title  + ", "+  base  + ", "+  foot  + "],
            "ggftO<Esc>.",
            [["ggftO<Esc>", "open one blank padding row above the title row"],
             [".", "repeat that opening once for the second padding row"]],
            "ascii-art-authoring §9g-10; authored frame-height padding B",
            "Add two blank padding rows above the alternate plus-framed title using the taught O-plus-dot route.",
            "The first O creates one blank row; dot must create the second while keeping title, base, and foot registered.",
        ),
    ],
}


EXPECTED_CARD_IDS = frozenset(REVIEW_VARIANTS)
